config/routes.rb
Rails.application.routes.draw do
  # get 'friends/show'

  devise_for :users
  get '/signup', to: 'users#sign_up'
  get '/login', to: 'users#sign_in'

  resources :posts do
    resources :comments
  end

  resources :friends, only: [] do
    collection do
      get :add_friend
      get :accept_friend
    end
  end

  resources :friends

  authenticated :user do
    root "dashboard#show"
  end

   unauthenticated do
    root 'home#index'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :content, presence: true, length: { maximum: 100 }

  def check_owner user
    self.user_id == user.id
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  # status - requested, accepted, rejected
  enum status: [ :requested, :accepted ]

  belongs_to :user
  validates :user_id, presence: true
  validates :friend_id, presence: true

  def self.check_friendship user_1, user_2
    friend = [false, nil]
    friendship = user_1.friendships.where(friend_id: user_2).first

    if friendship
      friend = [true, friendship]
    else
      friendship = Friendship.where(user_id: user_2, friend_id: user_1).first
      if friendship
        friend = [true, friendship]
      end
    end
    friend
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :title, presence:true, length: { maximum: 50}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :friendships, dependent: :destroy
  #before_action :authenticate_user!
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable,
       :confirmable

  def friends
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

   def index
   end
   
  def create
    puts '1111111111111111111111111'
    puts params.inspect

    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(user_id: current_user.id, content: params[:comment][:content])
    if @comment.valid?
      respond_to do |format|
        format.html 
        format.js
      end    
    else
      respond_to do |format|
        format.html 
        format.js
      end  
      # render 
    end  #    @comment = Comment.new(comment_params)
    # if @comment.save
    #   flash[:success] = "comment successful!"
  #           redirect_to comments_path
  #       else
  #         render 'new'
  #       end
   end
   
   def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
   end
   
   def update


   end
   
   def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @post.user_id == @comment.user_id
    @comment.destroy
      respond_to do |format|
        format.html do
          redirect_to post_path(@post)
        end
        format.js
      end

    end


    redirect_to post_path(@post)
    #redirect_to :action => 'posts/show', :id => @post
   end

   private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def new
    @user= User.new
  end

  def show
      #@user= User.find(params[:id])
    @posts = current_user.posts
    @users = User.all
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  # def new
  #   # @friend = Friendship.new
  # end 

  def add_friend
    # columns = user_id, friend_id, status
    # params = friend_id

    #  current_user as user
    # friendship = current_user.friendships.where(friend_id: params[:friend_id]).first

    # unless friendship
    #   # current_user as friend_id
    #   friendship = Friendship.where(user_id: params[:friend_id], friend_id: current_user.id).first
    #   unless friendship
    #     friendship = current_user.friendships.where(friend_id: params[:friend_id]).create
    #   end
    # end

    user_2 = User.find(params[:friend_id])
    friends = Friendship.check_friendship current_user, user_2
    unless friends[0]
      friends[1] = current_user.friendships.where(friend_id: params[:friend_id]).create
    end
    friends[1].requested!
    redirect_to root_path

    # @user= User.find(params[:user_id])
    # @friend= @user.friend.new(user_id: current_user.id, friend_id: user_id, friendship: false)
    #current_user.friendships.build()


  end

  def destroy
    user_2 = User.find(params[:id])
    friends = Friendship.check_friendship current_user, user_2
    #@friend = current_user.friendships.find(params[:friend_id])
    friends[1].destroy
    flash[:success] = "Request rejected"
    redirect_to root_url
  end

  def accept_friend
    user_2 = User.find(params[:friend_id])
    friends = Friendship.check_friendship current_user, user_2
    # if friends.update_attributes(friend_params)
    friends[1].accepted!
    redirect_to root_path
    # end

  end

  # def edit

  # end

  # def update
  # end
  private

  def friend_params
    #params.require(:friendship).permit(:status=1)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts =Post.all
	end

	def show
		@post= Post.find(params[:id])
    @comment = Comment.new
    # @user = @post.find(params[:user_id])
	end

	def new
		@post =Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post created!"
            redirect_to :action => 'show', :id => @post
        end
	end

	def update
		@post = Post.find(params[:id])

		if @post.update_attributes(post_params)
			redirect_to :action => 'show', :id => @post
		end
	end

	def destroy
		@post.destroy
		flash[:success] = "Post deleted"
		redirect_to root_url
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:content, :title)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def check_comment_owner comment, user
    comment.user_id == user.id
  end
end

app/views/comments/_comment.html.erb
<% @post.comments.each do |comment| %>
    <tr>
    	<% friends = Friendship.check_friendship current_user, comment.user %>
    		<% if friends[0] || current_user.id == comment.user.id %>
    			<td><%= comment.content %></td>
    			<td><%= comment.user.email %></td>
    			<td><%= comment.created_at %></td>
    			<%#= current_user.inspect %>
    			<%#= @post.inspect %>
    			<%#= comment.inspect %>
    			<%#= friends[1] %>
    			<td>
    			<% if comment.check_owner(current_user) %>
    				<%= link_to 'Edit', edit_post_comment_path(@post, comment), class: 'btn links' %>	
          <% end %>
          <% if current_user.id == comment.user_id || current_user.id == @post.user_id %>
          	<%= link_to 'Delete', post_comment_path(@post, comment) , method: :delete, data: {confirm: 'Are you sure?' }, remote: true, class: 'btn links'%>
          <% end %>
    		  </td>
    	<% end %>
    </tr>
<% end %>

app/views/comments/_index.html.erb
<h2><center>Post Comments</center></h2>
<div class="container">
	<% @post.comments.each do |comment| %>
		<div class="row">
			<span><%= comment.content %></span>
			<%= time_ago_in_words(comment.created_at) %>
			<%= link_to 'Edit', edit_comment_path(comment), class: 'btn links' %>
			<%= link_to 'Delete', comment_path(comment) , method: :delete, data: {confirm: 'Are you sure?' }, class: 'btn links'%>
	    <br><br>
  </div>
<% end %>
  
</div>

app/views/comments/create.js.erb
<%# if @comment.errors.any? %>
<%#= @comment.errors.full_message.html_safe() %>
<%# else %>
$('#com').html("<%=j render 'comments/comment' %>");
$('#comment_field').reset();
<%# end %>

app/views/comments/new.html.erb
<h2 class="h2_form">Add New Comment</h2>
<div class="row signup">
   <div class="col-md-3"></div>
   <%= form_for(@comment) do |p| %>
    <div class="col-md-6 form_main">

          <div class="field form-group">
               <%= p.label :comment %><br />
               <%= p.text_field :content, autofocus: true, class: 'form-control' %>
          </div>
          <div class="actions ">
               <%= p.submit "Comment", class: 'btn-default'%>
          </div>
    <% end %>

     <%#= render "devise/shared/links" %>
     </div>
        <div class="col-md-3"></div>
</div>

app/views/dashboard/show.html.erb
<div class="page-header">
  <h1>User <small>Dashboard</small></h1>
</div>

<h2><%#= current_user.email%></h2>

<p><%#= @posts.inspect %></p>

<p><%#= @posts.first.inspect %></p>
<div class="row ">
  <div class="col-md-3"></div>
  <div class="col-md-6 main"><p>Hello, <%= current_user.email%>!</p></div>
  <div class="col-md-3"></div>
</div>
<div class="row ">
  <div class="col-md-2"></div>
  <div class="col-md-8"><h2>Add Friends List</h2></div>
  <div class="col-md-2"></div>
</div>
<% @users.each do |user| %>
  <% if user.id != current_user.id %>
    <div class="row ">
      <div class="col-md-3"></div>
      <div class="col-md-4"><h4><%= user.email %></h4></div>
      <div class="col-md-5">
        <% friendship = Friendship.check_friendship current_user, user %>
        <!-- friend requested -->
        <% if friendship[0] && friendship[1].requested? && friendship[1].user_id == current_user.id %>
          <%= link_to 'Requested. Cancel?', '#' %>
        <% elsif friendship[0] && friendship[1].requested? && friendship[1].user_id == user.id %>
          <%= link_to 'Accept', accept_friend_friends_path(friend_id: user.id), class: 'btn links' %>
          <%= link_to 'Reject', friend_path(user), method: :delete, data: {confirm: 'Are you sure?' }, class: 'btn links' %>
        <!-- when friend -->
        <% elsif friendship[0] && friendship[1].accepted? %>
          <%= link_to 'Remove', '#' %>
        <!-- when request received -->
        <%# elsif friendship[0] && friendship[1].status == 0 %>

        <% else %>
          <%= link_to 'Add Friend', add_friend_friends_path(friend_id: user.id), class: 'btn links' %>
        <% end %>
      </div>  
    </div>
  <% end %>
<% end %>

app/views/friends/show.html.erb
<h1>Friends#show</h1>
<p>Find me in app/views/friends/show.html.erb</p>

app/views/home/index.html.erb
<div class="row ">
  <div class="col-md-3"></div>
  <div class="col-md-6 main"><p>Hello, Welcome to friend app!!</p></div>
  <div class="col-md-3"></div>
</div>

app/views/layouts/_footer.html.erb
<footer>
<div class="container">

<nav>
	
</nav>
</div>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-default header">
    <div class="navbar-header ">
      <a class="navbar-brand" href="#" style="float: left;">
        <img alt="Friend App" src="..." style="font-size: 16px;">
      </a>
       <ul class="nav nav-pills menu" style="float: right; margin-right: 30px;">
  <li role="presentation" class="active" ><%= link_to "Home" , root_path%></li>
  <% if not user_signed_in? %>
    <li role="presentation" ><%= link_to "Sign-Up" , new_user_registration_path %></li>
    <li role="presentation" ><%= link_to "Log-In" , new_user_session_path %></li>
  <% end %>
  <% if user_signed_in? %>
  <li role="presentation"><%= link_to "Edit profile", edit_user_registration_path %></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Post <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "All post", posts_path %></li>
      <li><%= link_to "Add New Post", new_post_path %></li>
    </ul>
  </li>
  <li role="presentation" ><%= link_to "Logout" , destroy_user_session_path, :method => :delete %></li>
  <% end %>

</ul>
    </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/edit.html.erb
<h2 class="h2_form">Edit Post</h2>
<div class="row signup">
	<div class="col-md-3"></div>
		<%= form_for(@post) do |p| %>

    		<div class="col-md-6 form_main">
   			   <div class="field form-group">
                <%= p.label :title %><br />
                <%= p.text_field :title, autofocus: true, class: 'form-control' %>
            </div>

            <div class="field form-group">
               <%= p.label :content %><br />
               <%= p.text_field :content, autofocus: true, class: 'form-control' %>
            </div>
            <div class="actions ">
               <%= p.submit "Save Change", class: 'btn-default'%>
            </div>
        <% end %>
        <%#= render "devise/shared/links" %>
    </div>
        <div class="col-md-3"></div>
</div>

app/views/posts/index.html.erb
<h2><center>Post List</center></h2>
<div class="container">
	<% @posts.each do |post| %>
	  <% friends = Friendship.check_friendship current_user, post.user %>
    	<% if friends[0] || current_user.id == post.user.id %>
				<div class="row post_col">
					<h3><%= post.title %></h3>
					<span><%= post.content %></span>
					<h5><%= time_ago_in_words(post.created_at) %></h5>
					<%= link_to 'Show', post_path(post), class: 'btn links' %>
					<%= link_to 'Edit', edit_post_path(post), class: 'btn links' %>
					<%= link_to 'Delete', post_path(post) , method: :delete, data: {confirm: 'Are you sure?' }, class: 'btn links'%>
	    		<br><br>
  			</div>
  			<% end %>
<% end %>
  
</div>

app/views/posts/new.html.erb
<h2 class="h2_form">Add New Post</h2>
<div class="row signup">
   <div class="col-md-3"></div>
   <%= form_for(@post) do |p| %>
    <div class="col-md-6 form_main">
   			   <div class="field form-group">
                <%= p.label :title %><br />
                <%= p.text_field :title, autofocus: true, class: 'form-control' %>
                </div>

          <div class="field form-group">
               <%= p.label :content %><br />
               <%= p.text_field :content, autofocus: true, class: 'form-control' %>
          </div>
          <div class="actions ">
               <%= p.submit "Post", class: 'btn-default'%>
          </div>
    <% end %>

     <%#= render "devise/shared/links" %>
     </div>
        <div class="col-md-3"></div>
</div>

app/views/posts/show.html.erb
<div class="panel panel-primary">
	<div class="panel-heading"><%= @post.title %></div>

  <div class="panel-body">

   <span class="content"><h4><%= @post.content %></h4></span> 
   <span class="timestamp"> posted <%= time_ago_in_words(@post.created_at) %> ago</span> 
  </div>
  
</div>

<h4>Comments</h4>
<table class="table">
    	<thead>
    		<tr>
    			<th>Comment</th>
    			<th>Comment by</th>
    			<th>Created At</th>
    			<th>action</th>
    		</tr>
    	</thead>
    	<tbody id='com'>
      	<%= render 'comments/comment' %>
      </tbody>
    </table>
    <br/>
    <br/>
 <%= form_for [@post, @comment], remote: true do |f| %>
   			   <div class="field form-group">
                <%= f.label :Comment %><br />
                <%= f.text_area :content, autofocus: true, class: 'form-control', id: 'comment_field' %>
            </div>
            <div class="actions ">
               <%= f.submit "Add Comment", class: 'btn-default'%>
            </div>
 <% end %>

<% if false %>
<%= form_for([@post, @comment]) do |p| %>
  <div class="field form-group">
     <%= p.label :content %><br />
     <%= p.text_field :content, autofocus: true, class: 'form-control' %>
  </div>
  <div class="actions ">
     <%= p.submit "Save Change", class: 'btn-default'%>
  </div> 
<% end %>
<% end %>



	